name: hfradar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - xarray=0.16.1
  - netcdf4=1.5.4
  - cartopy
  - geopandas
  - oceans
  - jupyter
  - numba
  - pytest
  - cmocean
  - dask
  - bump2version=0.5.11
  - wheel=0.33.6
  - flake8=3.7.8
  - tox=3.14.0
  - coverage=4.5.4
  - Sphinx=1.8.5
  - Click=7.1.2
