name: codar_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - netcdf4
  - dask
  - sqlalchemy
  - mysql-connector-python=2.2.3=py36_0
  - scipy
  - geopandas
  - cartopy
  - oceans
  - gsw
  - seawater
  - jupyter
  - numba
  - pytest
