name: hfradarpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.2
  - xarray
  - netcdf4
  - pyproj
  # - bottleneck [--no-deps]
  # - dask [--no-deps]
  # - geopandas [--no-deps]
  - cartopy [--no-deps]
  - cmocean [--no-deps]
  # - jupyterlab [--no-deps]
  # - nb_conda_kernels [--no-deps]
