name: hfradar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - geopandas
  # - pytest [--no-deps]
  # - cartopy [--no-deps]
  # - cmocean [--no-deps]