name: codar_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - xarray=0.16.1
  - netcdf4=1.5.4
  - cartopy
  - geopandas
  - sqlalchemy
  - mysql-connector-python
  - oceans
  - jupyter
  - numba
  - pytest
  - cmocean
