name: hfradar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - netcdf4
  - geopandas
  - bottleneck [--no-deps]
  - dask [--no-deps]
  - pytest [--no-deps]
  - cartopy [--no-deps]
  - cmocean [--no-deps]